spring:
  application:
    name: task-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false
  web:
    locale: en
logging:
  level:
    root: info